### ISSUE TITLE
Wrong filenames for logging version of library (Windows)

### ISSUE THREAD

**Issue by GitGhillie** [lebedec/libfmod#17]
Hi!

I think I found a little issue in https://github.com/lebedec/libfmod/blob/main/libfmod/build.rs: When using the `debug` feature the expected library names become fmod_vcL and fmodstudio_vcL, but when you download the libs from FMOD you get fmodL_vc and fmodstudioL_vc. Bit unfortunate that the FMOD library names are inconsistent like that

**Comment by lebedec** [comment]
Hi! Thanks! 

Is it critical for you?  If not, I'd like to postpone this fix until the next iteration of development =)

**Comment by GitGhillie** [comment]
Not critical in the slightest! I can just rename the libs for now so take all the time you want :)

**Comment by lebedec** [comment]
@GitGhillie did you start seeing logs in the console after using logging versions of FMOD libs?

In my environment on Windows it not working.

**Comment by lebedec** [comment]
Several sub-tasks within this issue:
- rename crate feature `debug` to more appropriate `logging`
- provide wrapper for `FMOD_Debug_Initialize` and usage example

FMOD docs: https://www.fmod.com/docs/2.01/api/core-api-common.html#debug_initialize

**Comment by GitGhillie** [comment]
> @GitGhillie did you start seeing logs in the console after using logging versions of FMOD libs?
> 
> In my environment on Windows it not working.

Using `FMOD_Debug_Initialize(FMOD_DEBUG_LEVEL_LOG, FMOD_DEBUG_MODE_TTY, None, null_mut());` I'm not getting anything either (Linux). On the plugin side I also tried logging a message with FMOD_DSP_LOG_FUNC, but nothing showed up in the FMOD Studio console either (in this case I did not call FMOD_Debug_Initialize as I assumed FMOD Studio would init that properly)...

**Comment by lebedec** [comment]
Original issue fixed in `2.222.4`

Otherwise it's not very clear how logging version of FMOD libs works 🤷‍♂️

- I tried logging to a file `FMOD_DEBUG_MODE_FILE`, it works in my Windows environment
- On MacOS logging to console works by default without calling `FMOD_Debug_Initialize` (at least I've seen it before)
