### ISSUE TITLE
[BUG] library fails to create an instance of an event

### ISSUE THREAD

**Issue by BurAndBY** [lebedec/libfmod#22]
After a while of trying to debug why my app isn't playing FMOD audio, I've finally found that the app triggers an exception on this line
![image](https://github.com/user-attachments/assets/a180fd16-6bd6-4a10-bf4f-ef366f5f35d0)
`Exception 0xc000041d encountered at address 0x7ff7b73921a3`

Here is my init of the FMOD libraries

```rs
unsafe fn initialize_studio(&self) -> Result<Studio, AudioProcessingError> {
        let studio = Studio::create()
            .map_err(|e| AudioProcessingError::StudioError(format!("Studio creation failed: {}", e)))?;

        let system = studio
            .get_core_system()
            .map_err(|e| AudioProcessingError::StudioError(format!("Core system acquisition failed: {}", e)))?;

        system
            .set_software_format(
                Some(48000),
                Some(SpeakerMode::Default),
                Some(2),
            )
            .map_err(|e| AudioProcessingError::StudioError(format!("Software format setup failed: {}", e)))?;

        studio
            .initialize(
                1024,
                ffi::FMOD_STUDIO_INITFLAGS::default(),
                ffi::FMOD_INITFLAGS::default(),
                None,
            )
            .map_err(|e| AudioProcessingError::StudioError(format!("Studio initialization failed: {}", e)))?;

        ffi::FMOD_Debug_Initialize(
            ffi::FMOD_DEBUG_TYPE_TRACE,
            ffi::FMOD_DEBUG_MODE_FILE,
            None,
            log_filename.as_ptr()
        );
        Ok(studio)
    }
```

**Comment by lebedec** [comment]
Hi! I rarely use the debugger, so it's not very clear where the problem is:

> Exception 0xc000041d encountered at address 0x7ff7b73921a3

1. There are no exceptions in Rust, right? =) Is this the debugger output or record in FMOD logs?
2. Can you provide more environment info?

```bash
uname -a
rustc --version
rustup toolchain list
FMOD version
```
It looks like you have some sort of runtime mismatch: used specific Rust target or wrong FMOD libraries (x86 instead of x64), etc

**Comment by BurAndBY** [comment]
1. This is the Jetbrains RustRover's default debugger output. 
2. Microsoft Windows 11 [Version 10.0.22621.4317]
    rustc 1.81.0 (eeb90cda1 2024-09-04)
    stable-x86_64-pc-windows-msvc (default)
3. Log output from FMOD
```
[LOG] System::create                           : Header version = 2.02.22. Current version = 2.02.24.
[LOG] Manager::init                            : maxchannels = 1024 studioflags = 00000000 flags 00000000 extradriverdata 0000000000000000.
[LOG] SystemI::init                            : Initialize version=20224 (146338), maxchannels=1024, flags=0x00020000
[LOG] SystemI::setOutputInternal               : Setting output to 'FMOD WASAPI Output'
[LOG] OutputWASAPI::init                       : Mix Format (WAVEFORMATEX): wFormatTag=0xFFFE, nChannels=2, nSamplesPerSec=48000, nAvgBytesPerSec=384000, nBlockAlign=8, wBitsPerSample=32, cbSize=22.
[LOG] OutputWASAPI::init                       : Mix Format (WAVEFORMATEXTENSIBLE): wValidBitsPerSample=32, dwChannelMask=0x00000003, SubFormat=00000003-0000-0010-8000-00AA00389B71.
[LOG] OutputWASAPI::init                       : Output buffer size: 4096 samples, latency: 0.00ms, period: 10.00ms, DSP buffer: 1024 * 4
[LOG] Thread::initThread                       : Init FMOD stream thread. Affinity: 0x4000000000000003, Priority: 0xFFFF7FFB, Stack Size: 98304, Semaphore: No, Sleep Time: 10, Looping: Yes.
[LOG] Thread::initThread                       : Init FMOD mixer thread. Affinity: 0x4000000000000001, Priority: 0xFFFF7FFA, Stack Size: 81920, Semaphore: No, Sleep Time: 0, Looping: Yes.
[LOG] AsyncManager::init                       : manager 00000168919186E8 isAsync 1 updatePeriod 0.02
[LOG] Thread::initThread                       : Init FMOD Studio update thread. Affinity: 0x4000000000000002, Priority: 0xFFFF7FFD, Stack Size: 98304, Semaphore: No, Sleep Time: 1, Looping: No.
[LOG] AsyncManager::init                       : done
[LOG] PlaybackSystem::init                     : 
[LOG] Thread::initThread                       : Init FMOD Studio sample load thread. Affinity: 0x4000000000000003, Priority: 0xFFFF7FFD, Stack Size: 98304, Semaphore: No, Sleep Time: 1, Looping: No.
[LOG] PlaybackSystem::init                     : done
[LOG] Thread::initThread                       : Init FMOD Studio bank load thread. Affinity: 0x4000000000000003, Priority: 0xFFFF7FFD, Stack Size: 98304, Semaphore: No, Sleep Time: 1, Looping: No.
[LOG] Manager::init                            : done.
```

The application shows up in the volume mixer, which means windows thinks it made some sound, but with volume 0.95-1000 it just did not do anything (docs say its from 0-1 but neither 0.95 nor 100 also did sound)

BTW, for some reason the library sometimes fails to find events when going through the banks events

Code: (removed the code that just skips the crashing events, cause that's not ideal)
```rs
fn process_single_bank(&mut self, studio: &Studio, bank_path: &Path) -> Result<(), AudioProcessingError> {
        let bank_path_str = bank_path
            .to_str()
            .ok_or_else(|| AudioProcessingError::PathError(format!("Invalid bank path: {:?}", bank_path)))?;

        let bank = studio
            .load_bank_file(bank_path_str, ffi::FMOD_STUDIO_LOAD_BANK_NORMAL)
            .map_err(|e| AudioProcessingError::BankError(format!("Bank loading failed for {}: {}", bank_path_str, e)))?;

        let event_count = bank
            .get_event_count()
            .map_err(|e| AudioProcessingError::BankError(format!("Failed to get event count: {}", e)))?;

        let events = bank
            .get_event_list(event_count)
            .map_err(|e| AudioProcessingError::BankError(format!("Failed to get event list: {}", e)))?;

        for event in events {

            //if let Ok(path) = event.get_path() {
                self.processed_files.push(event.get_path().unwrap());
                self.event_list.push(event);
            //} else {
                //self.log(format!("Skipped invalid event in bank: {:?}", bank_path).as_str());
            //}
        }

        Ok(())
    }
```

Output: 
```
called `Result::unwrap()` on an `Err` value: Fmod { function: "FMOD_Studio_EventDescription_GetPath", code: 74, message: "The requested event, parameter, bus or vca could not be found." }
```

**Comment by BurAndBY** [comment]
Here is the full code if anything catches your eye: https://bpa.st/EJQX2
And the banks that trigger the error: https://files.catbox.moe/a66pyv.zip

**Comment by lebedec** [comment]
So, there is no exception. FMOD returns error and unwrapping this error crushes your app. Do I understand correctly?

Before working with string, we should load `Master` and `Master.strings` banks. In your code I don't see when it happens. Maybe errors occur some times because you not control order of banks loading? If the `Master.strings` is not loaded before you use `get_path` method, that would explain this error:

> The requested event, parameter, bus or vca could not be found

Event not found because string path not loaded.

**Comment by BurAndBY** [comment]
> So, there is no exception. FMOD returns error and unwrapping this error crushes your app. Do I understand correctly?
> 
> Before working with string, we should load `Master` and `Master.strings` banks. In your code I don't see when it happens. Maybe errors occur some times because you not control order of banks loading? If the `Master.strings` is not loaded before you use `get_path` method, that would explain this error:
> 
> > The requested event, parameter, bus or vca could not be found
> 
> Event not found because string path not loaded.


Sorry, I have sent the wrong code, here is the right one (with the later mentioned changes): https://bpa.st/CX72I
The exception happens if I skip the events that could not be found and try to create an instance of the events that are found
I have modified the bank loading code and sorted it so the strings load first, this fixed the "event not found" error and now all the events load correctly, but that did not fix the inability to create a instance and there is still no sound on event playback.

**Comment by lebedec** [comment]
So... I can recommend you do not `unwrap` each result. It bad practice at all. Makes application unstable, debugging problematic, issue solving confusing, etc =) I think your problem will be solved fast if you just handle your errors like this:

```rust
egui::CentralPanel::default().show(ctx, |ui| {
	if ui.interaction() {
		if let Err(error) = do_my_stuff() {
			log!("unable to do my stuff because of {error:?}")
		}
	}
})

fn do_my_stuff() -> Result<(), Error> {
	let event = self.selected_event?;
	let instance = create_instance()?;
	let path = instance.get_path()?;
	... etc
}
```

This crate do not contain any logic, it just wrapper for FMOD. And I don't provide support for FMOD using. You'd better write your problem on the official forum https://qa.fmod.com for help.

And of course you can create issue here if it issue of `libfmod`: inccorrect API, segfault, heap memory corruption or any FFI problems.
