### ISSUE TITLE
Dsp::get_parameter_data usage for getting the FFT spectrum of a channel

### ISSUE THREAD

**Issue by fililip** [lebedec/libfmod#5]
There doesn't seem to be an easy way of accessing FFT spectrum information of a channel.

Dereferencing pointers to `libfmod::ffi::FMOD_DSP_PARAMETER_FFT` after receiving them via calls to `Dsp::get_parameter_data()` in unsafe blocks doesn't sound like the best idea (it doesn't even return any data anyway, which renders the whole procedure useless), while the FFT DSP feature of FMOD is one that does come in handy and should, in my opinion, be properly implemented as part of the binding.

Is there something that could be done here to fix this?

**Comment by lebedec** [comment]
I think this can be improved. 

There are two ways:
- Add a new abstraction layer, another wrapper to implement special cases like this manually.
- Improve a generator. Although the library is fully generated, I made a some preparations that allow to override the generation results.

The first way is huge solution decision, now it impossible. But, I can try improve generator to eliminate unsafe blocks and deref pointers in wrapper.

It will help a lot If you send me code examples where `FMOD_DSP_PARAMETER_FFT` parameter is used (any C/C++ code possible) or write your vision of `Dsp::get_parameter_data()` function signature and usage for example.

**Comment by fililip** [comment]
Here's a code snippet from my audio player written in C# (I used the official FMOD binding for C#):

```csharp
IntPtr fftData;
uint fftLength;

fftDSP.getParameterData((int)DSP_FFT.SPECTRUMDATA, out fftData, out fftLength);

DSP_PARAMETER_FFT fft = (DSP_PARAMETER_FFT)Marshal.PtrToStructure(fftData, typeof(DSP_PARAMETER_FFT));
fft.getSpectrum(ref spectrum);

if (fft.numchannels > 0)
{
  for (int i = 0; i < values.GetLength(1); i++)
  {
    ...
```

`IntPtr` is the "safe" pointer type in C#.
The `DSP_PARAMTER_FFT.getSpectum()` function in the C# binding returns the `.spectrum` parameter of the structure (`float[][]`).

The same thing applies to C/C++: you call `getParameterData()` with a pointer to an instance of that structure cast to `void**` to get your FFT data, so something along the lines of:

```cpp
FMOD_DSP_PARAMETER_FFT *fft;
fftdsp->getParameterData(FMOD_DSP_FFT_SPECTRUMDATA, (void **)&fft, 0, 0, 0));
for (int channel = 0; channel < fft->numchannels; channels++)
{
    for (int bin = 0; bin < fft->length; bin++)
    {
        float val = fft->spectrum[channel][bin];
    }
}
```

Hope that clears things up!

**Comment by lebedec** [comment]
Thanks, I'll try to fix it.

**Comment by lebedec** [comment]
The problem more difficult than I thought because of design `FMOD_DSP_GetParameterData`. 
This function too generic and used not only for any DSP type but for any user defined data. 
Also FMOD do not provide any typing info for safe pointer casting.

So, there is no ease way to handle `*c_void`. I have no idea how to implement this without reworking high level design of library.

But I implemented `TryFrom` trait specific for `DspParameterFft` to simplify safe usage. Hope that it helps you:

```rust
let sound = system.create_sound("./data/beep.wav", FMOD_DEFAULT, None)?;
let channel = system.play_sound(sound, None, false)?;
let dsp = system.create_dsp_by_type(DspType::Fft)?;
channel.add_dsp(0, dsp)?;
while channel.is_playing()? {
    // do something
}
let fft = DspParameterFft::try_from(dsp)?;
for channel in fft.spectrum.iter() {
    let sum: f32 = channel.iter().sum();
    println!("length: {}, sum: {}", fft.length, sum);
}
```
