### ISSUE TITLE
Get location of Fmod libraries from environment

### ISSUE THREAD

**Issue by judemille** [lebedec/libfmod#9]
It is idiomatic to use an environment variable in a build script to determine the location of dependencies not provided, and then produce a build error if the environment variable is not set. I would recommend doing this.

**Comment by lebedec** [comment]
Hi! Thanks for the recommendation, but it is not relevant. 

The project has been created for internal use only, there is no any use cases except for libmod. I think it's quite acceptable here such practices like hardcoding default location of libraries. 

Also it designed as a simple command line tool. And it is absolutely correct to use command arguments to provide source/destinations folders. Speaking of idiomaticy, it is idiomatic for "command line language" =) 

But you can still use enrionment variables if you wish, just pass it in command arguments.
